version: '3'

services:
  todoback:
    image: todobackend
    ports:
      - 3001:3001
    networks:
      - todo-app
    restart: always

  todofront:
    image: todofrontend
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
      - REACT_APP_API_PORT=3001
    networks:
      - todo-app
    restart: always

  todotests:
    image: todotests
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofront
      - FRONT_PORT=3000
    networks:
      - todo-app
    restart: always

networks: 
  todo-app: